[device]
vendor = 0x045e
product = 0x0921

[actions]
single = ["KEY_LEFTCTRL", "KEY_LEFTSHIFT", "KEY_F23"]
double = ["KEY_LEFTMETA", "KEY_LEFTSHIFT", "KEY_SYSRQ"]
hold = ["KEY_LEFTCTRL", "KEY_LEFTSHIFT", "KEY_F24"]
